export const repoResponse = [
	{
		id: 752920523,
		node_id: 'R_kgDOLOCnyw',
		name: 'chrono-core',
		full_name: 'ubemacapuno/chrono-core',
		private: false,
		owner: {
			login: 'ubemacapuno',
			id: 97559559,
			node_id: 'U_kgDOBdCkBw',
			avatar_url: 'https://avatars.githubusercontent.com/u/97559559?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ubemacapuno',
			html_url: 'https://github.com/ubemacapuno',
			followers_url: 'https://api.github.com/users/ubemacapuno/followers',
			following_url: 'https://api.github.com/users/ubemacapuno/following{/other_user}',
			gists_url: 'https://api.github.com/users/ubemacapuno/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ubemacapuno/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ubemacapuno/subscriptions',
			organizations_url: 'https://api.github.com/users/ubemacapuno/orgs',
			repos_url: 'https://api.github.com/users/ubemacapuno/repos',
			events_url: 'https://api.github.com/users/ubemacapuno/events{/privacy}',
			received_events_url: 'https://api.github.com/users/ubemacapuno/received_events',
			type: 'User',
			site_admin: false
		},
		html_url: 'https://github.com/ubemacapuno/chrono-core',
		description:
			' ChronoCore is a Python + React + TypeScript tool for real-time monitoring of GPU, CPU, and RAM, using WebSockets for live updates, displayed on a Raspberry Pi. ',
		fork: false,
		url: 'https://api.github.com/repos/ubemacapuno/chrono-core',
		forks_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/forks',
		keys_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/keys{/key_id}',
		collaborators_url:
			'https://api.github.com/repos/ubemacapuno/chrono-core/collaborators{/collaborator}',
		teams_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/teams',
		hooks_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/hooks',
		issue_events_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/issues/events{/number}',
		events_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/events',
		assignees_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/assignees{/user}',
		branches_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/branches{/branch}',
		tags_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/tags',
		blobs_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/git/blobs{/sha}',
		git_tags_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/git/tags{/sha}',
		git_refs_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/git/refs{/sha}',
		trees_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/git/trees{/sha}',
		statuses_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/statuses/{sha}',
		languages_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/languages',
		stargazers_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/stargazers',
		contributors_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/contributors',
		subscribers_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/subscribers',
		subscription_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/subscription',
		commits_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/commits{/sha}',
		git_commits_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/git/commits{/sha}',
		comments_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/comments{/number}',
		issue_comment_url:
			'https://api.github.com/repos/ubemacapuno/chrono-core/issues/comments{/number}',
		contents_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/contents/{+path}',
		compare_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/compare/{base}...{head}',
		merges_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/merges',
		archive_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/{archive_format}{/ref}',
		downloads_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/downloads',
		issues_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/issues{/number}',
		pulls_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/pulls{/number}',
		milestones_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/milestones{/number}',
		notifications_url:
			'https://api.github.com/repos/ubemacapuno/chrono-core/notifications{?since,all,participating}',
		labels_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/labels{/name}',
		releases_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/releases{/id}',
		deployments_url: 'https://api.github.com/repos/ubemacapuno/chrono-core/deployments',
		created_at: '2024-02-05T05:25:55Z',
		updated_at: '2024-02-07T21:11:52Z',
		pushed_at: '2024-02-05T05:31:10Z',
		git_url: 'git://github.com/ubemacapuno/chrono-core.git',
		ssh_url: 'git@github.com:ubemacapuno/chrono-core.git',
		clone_url: 'https://github.com/ubemacapuno/chrono-core.git',
		svn_url: 'https://github.com/ubemacapuno/chrono-core',
		homepage: '',
		size: 52,
		stargazers_count: 0,
		watchers_count: 0,
		language: 'TypeScript',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: 'public',
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: 'main',
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true
		},
		temp_clone_token: '',
		network_count: 0,
		subscribers_count: 1
	},
	{
		id: 734202441,
		node_id: 'R_kgDOK8MKSQ',
		name: 'svelte-step-bro',
		full_name: 'ubemacapuno/svelte-step-bro',
		private: false,
		owner: {
			login: 'ubemacapuno',
			id: 97559559,
			node_id: 'U_kgDOBdCkBw',
			avatar_url: 'https://avatars.githubusercontent.com/u/97559559?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ubemacapuno',
			html_url: 'https://github.com/ubemacapuno',
			followers_url: 'https://api.github.com/users/ubemacapuno/followers',
			following_url: 'https://api.github.com/users/ubemacapuno/following{/other_user}',
			gists_url: 'https://api.github.com/users/ubemacapuno/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ubemacapuno/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ubemacapuno/subscriptions',
			organizations_url: 'https://api.github.com/users/ubemacapuno/orgs',
			repos_url: 'https://api.github.com/users/ubemacapuno/repos',
			events_url: 'https://api.github.com/users/ubemacapuno/events{/privacy}',
			received_events_url: 'https://api.github.com/users/ubemacapuno/received_events',
			type: 'User',
			site_admin: false
		},
		html_url: 'https://github.com/ubemacapuno/svelte-step-bro',
		description:
			'A modern SvelteKit application designed for CAD professionals, offering a free tool for viewing STEP files. This application utilizes Three.js and occt-import-js, ensuring high-performance 3D modeling without the need for any licensing.',
		fork: false,
		url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro',
		forks_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/forks',
		keys_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/keys{/key_id}',
		collaborators_url:
			'https://api.github.com/repos/ubemacapuno/svelte-step-bro/collaborators{/collaborator}',
		teams_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/teams',
		hooks_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/hooks',
		issue_events_url:
			'https://api.github.com/repos/ubemacapuno/svelte-step-bro/issues/events{/number}',
		events_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/events',
		assignees_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/assignees{/user}',
		branches_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/branches{/branch}',
		tags_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/tags',
		blobs_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/git/blobs{/sha}',
		git_tags_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/git/tags{/sha}',
		git_refs_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/git/refs{/sha}',
		trees_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/git/trees{/sha}',
		statuses_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/statuses/{sha}',
		languages_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/languages',
		stargazers_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/stargazers',
		contributors_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/contributors',
		subscribers_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/subscribers',
		subscription_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/subscription',
		commits_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/commits{/sha}',
		git_commits_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/git/commits{/sha}',
		comments_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/comments{/number}',
		issue_comment_url:
			'https://api.github.com/repos/ubemacapuno/svelte-step-bro/issues/comments{/number}',
		contents_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/contents/{+path}',
		compare_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/compare/{base}...{head}',
		merges_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/merges',
		archive_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/{archive_format}{/ref}',
		downloads_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/downloads',
		issues_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/issues{/number}',
		pulls_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/pulls{/number}',
		milestones_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/milestones{/number}',
		notifications_url:
			'https://api.github.com/repos/ubemacapuno/svelte-step-bro/notifications{?since,all,participating}',
		labels_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/labels{/name}',
		releases_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/releases{/id}',
		deployments_url: 'https://api.github.com/repos/ubemacapuno/svelte-step-bro/deployments',
		created_at: '2023-12-21T05:44:43Z',
		updated_at: '2024-02-05T19:01:54Z',
		pushed_at: '2024-02-06T00:04:13Z',
		git_url: 'git://github.com/ubemacapuno/svelte-step-bro.git',
		ssh_url: 'git@github.com:ubemacapuno/svelte-step-bro.git',
		clone_url: 'https://github.com/ubemacapuno/svelte-step-bro.git',
		svn_url: 'https://github.com/ubemacapuno/svelte-step-bro',
		homepage: 'https://stepbro.vercel.app',
		size: 606,
		stargazers_count: 0,
		watchers_count: 0,
		language: 'Svelte',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: ['step', 'svelte', 'sveltekit', 'threejs'],
		visibility: 'public',
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: 'main',
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true
		},
		temp_clone_token: '',
		network_count: 0,
		subscribers_count: 1
	},
	{
		id: 696581573,
		node_id: 'R_kgDOKYT9xQ',
		name: 'rep-log',
		full_name: 'ubemacapuno/rep-log',
		private: false,
		owner: {
			login: 'ubemacapuno',
			id: 97559559,
			node_id: 'U_kgDOBdCkBw',
			avatar_url: 'https://avatars.githubusercontent.com/u/97559559?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ubemacapuno',
			html_url: 'https://github.com/ubemacapuno',
			followers_url: 'https://api.github.com/users/ubemacapuno/followers',
			following_url: 'https://api.github.com/users/ubemacapuno/following{/other_user}',
			gists_url: 'https://api.github.com/users/ubemacapuno/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ubemacapuno/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ubemacapuno/subscriptions',
			organizations_url: 'https://api.github.com/users/ubemacapuno/orgs',
			repos_url: 'https://api.github.com/users/ubemacapuno/repos',
			events_url: 'https://api.github.com/users/ubemacapuno/events{/privacy}',
			received_events_url: 'https://api.github.com/users/ubemacapuno/received_events',
			type: 'User',
			site_admin: false
		},
		html_url: 'https://github.com/ubemacapuno/rep-log',
		description:
			'Enhance your exercise regimen with RepLog, a React/TypeScript app which includes a responsive UI made with Tailwind CSS. It allows you to track your reps and plan your workouts conveniently, keeping all data stored on your device.',
		fork: false,
		url: 'https://api.github.com/repos/ubemacapuno/rep-log',
		forks_url: 'https://api.github.com/repos/ubemacapuno/rep-log/forks',
		keys_url: 'https://api.github.com/repos/ubemacapuno/rep-log/keys{/key_id}',
		collaborators_url:
			'https://api.github.com/repos/ubemacapuno/rep-log/collaborators{/collaborator}',
		teams_url: 'https://api.github.com/repos/ubemacapuno/rep-log/teams',
		hooks_url: 'https://api.github.com/repos/ubemacapuno/rep-log/hooks',
		issue_events_url: 'https://api.github.com/repos/ubemacapuno/rep-log/issues/events{/number}',
		events_url: 'https://api.github.com/repos/ubemacapuno/rep-log/events',
		assignees_url: 'https://api.github.com/repos/ubemacapuno/rep-log/assignees{/user}',
		branches_url: 'https://api.github.com/repos/ubemacapuno/rep-log/branches{/branch}',
		tags_url: 'https://api.github.com/repos/ubemacapuno/rep-log/tags',
		blobs_url: 'https://api.github.com/repos/ubemacapuno/rep-log/git/blobs{/sha}',
		git_tags_url: 'https://api.github.com/repos/ubemacapuno/rep-log/git/tags{/sha}',
		git_refs_url: 'https://api.github.com/repos/ubemacapuno/rep-log/git/refs{/sha}',
		trees_url: 'https://api.github.com/repos/ubemacapuno/rep-log/git/trees{/sha}',
		statuses_url: 'https://api.github.com/repos/ubemacapuno/rep-log/statuses/{sha}',
		languages_url: 'https://api.github.com/repos/ubemacapuno/rep-log/languages',
		stargazers_url: 'https://api.github.com/repos/ubemacapuno/rep-log/stargazers',
		contributors_url: 'https://api.github.com/repos/ubemacapuno/rep-log/contributors',
		subscribers_url: 'https://api.github.com/repos/ubemacapuno/rep-log/subscribers',
		subscription_url: 'https://api.github.com/repos/ubemacapuno/rep-log/subscription',
		commits_url: 'https://api.github.com/repos/ubemacapuno/rep-log/commits{/sha}',
		git_commits_url: 'https://api.github.com/repos/ubemacapuno/rep-log/git/commits{/sha}',
		comments_url: 'https://api.github.com/repos/ubemacapuno/rep-log/comments{/number}',
		issue_comment_url: 'https://api.github.com/repos/ubemacapuno/rep-log/issues/comments{/number}',
		contents_url: 'https://api.github.com/repos/ubemacapuno/rep-log/contents/{+path}',
		compare_url: 'https://api.github.com/repos/ubemacapuno/rep-log/compare/{base}...{head}',
		merges_url: 'https://api.github.com/repos/ubemacapuno/rep-log/merges',
		archive_url: 'https://api.github.com/repos/ubemacapuno/rep-log/{archive_format}{/ref}',
		downloads_url: 'https://api.github.com/repos/ubemacapuno/rep-log/downloads',
		issues_url: 'https://api.github.com/repos/ubemacapuno/rep-log/issues{/number}',
		pulls_url: 'https://api.github.com/repos/ubemacapuno/rep-log/pulls{/number}',
		milestones_url: 'https://api.github.com/repos/ubemacapuno/rep-log/milestones{/number}',
		notifications_url:
			'https://api.github.com/repos/ubemacapuno/rep-log/notifications{?since,all,participating}',
		labels_url: 'https://api.github.com/repos/ubemacapuno/rep-log/labels{/name}',
		releases_url: 'https://api.github.com/repos/ubemacapuno/rep-log/releases{/id}',
		deployments_url: 'https://api.github.com/repos/ubemacapuno/rep-log/deployments',
		created_at: '2023-09-26T03:18:28Z',
		updated_at: '2024-02-05T19:02:12Z',
		pushed_at: '2024-01-22T15:38:36Z',
		git_url: 'git://github.com/ubemacapuno/rep-log.git',
		ssh_url: 'git@github.com:ubemacapuno/rep-log.git',
		clone_url: 'https://github.com/ubemacapuno/rep-log.git',
		svn_url: 'https://github.com/ubemacapuno/rep-log',
		homepage: 'https://rep-log.vercel.app',
		size: 167,
		stargazers_count: 0,
		watchers_count: 0,
		language: 'TypeScript',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: false,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: ['localstorage', 'react', 'vite'],
		visibility: 'public',
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: 'main',
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true
		},
		temp_clone_token: '',
		network_count: 0,
		subscribers_count: 1
	},
	{
		id: 618993351,
		node_id: 'R_kgDOJOUWxw',
		name: 'foodie-blog-sveltekit',
		full_name: 'ubemacapuno/foodie-blog-sveltekit',
		private: false,
		owner: {
			login: 'ubemacapuno',
			id: 97559559,
			node_id: 'U_kgDOBdCkBw',
			avatar_url: 'https://avatars.githubusercontent.com/u/97559559?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ubemacapuno',
			html_url: 'https://github.com/ubemacapuno',
			followers_url: 'https://api.github.com/users/ubemacapuno/followers',
			following_url: 'https://api.github.com/users/ubemacapuno/following{/other_user}',
			gists_url: 'https://api.github.com/users/ubemacapuno/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ubemacapuno/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ubemacapuno/subscriptions',
			organizations_url: 'https://api.github.com/users/ubemacapuno/orgs',
			repos_url: 'https://api.github.com/users/ubemacapuno/repos',
			events_url: 'https://api.github.com/users/ubemacapuno/events{/privacy}',
			received_events_url: 'https://api.github.com/users/ubemacapuno/received_events',
			type: 'User',
			site_admin: false
		},
		html_url: 'https://github.com/ubemacapuno/foodie-blog-sveltekit',
		description:
			'A SvelteKit recipe hub utilizing MongoDB, AuthJS, & OpenAI for a seamless, ad-free culinary journey. Designed for simplicity and efficient recipe management.',
		fork: false,
		url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit',
		forks_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/forks',
		keys_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/keys{/key_id}',
		collaborators_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/collaborators{/collaborator}',
		teams_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/teams',
		hooks_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/hooks',
		issue_events_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/issues/events{/number}',
		events_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/events',
		assignees_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/assignees{/user}',
		branches_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/branches{/branch}',
		tags_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/tags',
		blobs_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/git/blobs{/sha}',
		git_tags_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/git/tags{/sha}',
		git_refs_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/git/refs{/sha}',
		trees_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/git/trees{/sha}',
		statuses_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/statuses/{sha}',
		languages_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/languages',
		stargazers_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/stargazers',
		contributors_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/contributors',
		subscribers_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/subscribers',
		subscription_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/subscription',
		commits_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/commits{/sha}',
		git_commits_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/git/commits{/sha}',
		comments_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/comments{/number}',
		issue_comment_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/issues/comments{/number}',
		contents_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/contents/{+path}',
		compare_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/compare/{base}...{head}',
		merges_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/merges',
		archive_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/{archive_format}{/ref}',
		downloads_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/downloads',
		issues_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/issues{/number}',
		pulls_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/pulls{/number}',
		milestones_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/milestones{/number}',
		notifications_url:
			'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/notifications{?since,all,participating}',
		labels_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/labels{/name}',
		releases_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/releases{/id}',
		deployments_url: 'https://api.github.com/repos/ubemacapuno/foodie-blog-sveltekit/deployments',
		created_at: '2023-03-26T00:00:02Z',
		updated_at: '2024-02-05T19:03:52Z',
		pushed_at: '2024-01-19T22:31:06Z',
		git_url: 'git://github.com/ubemacapuno/foodie-blog-sveltekit.git',
		ssh_url: 'git@github.com:ubemacapuno/foodie-blog-sveltekit.git',
		clone_url: 'https://github.com/ubemacapuno/foodie-blog-sveltekit.git',
		svn_url: 'https://github.com/ubemacapuno/foodie-blog-sveltekit',
		homepage: 'https://foodie-blog-sveltekit.vercel.app',
		size: 511,
		stargazers_count: 0,
		watchers_count: 0,
		language: 'Svelte',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 7,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: 'public',
		forks: 0,
		open_issues: 7,
		watchers: 0,
		default_branch: 'main',
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true
		},
		temp_clone_token: '',
		network_count: 0,
		subscribers_count: 2
	},
	{
		id: 572204696,
		node_id: 'R_kgDOIhsmmA',
		name: 'capa-tracker-sveltekit',
		full_name: 'ubemacapuno/capa-tracker-sveltekit',
		private: false,
		owner: {
			login: 'ubemacapuno',
			id: 97559559,
			node_id: 'U_kgDOBdCkBw',
			avatar_url: 'https://avatars.githubusercontent.com/u/97559559?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ubemacapuno',
			html_url: 'https://github.com/ubemacapuno',
			followers_url: 'https://api.github.com/users/ubemacapuno/followers',
			following_url: 'https://api.github.com/users/ubemacapuno/following{/other_user}',
			gists_url: 'https://api.github.com/users/ubemacapuno/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ubemacapuno/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ubemacapuno/subscriptions',
			organizations_url: 'https://api.github.com/users/ubemacapuno/orgs',
			repos_url: 'https://api.github.com/users/ubemacapuno/repos',
			events_url: 'https://api.github.com/users/ubemacapuno/events{/privacy}',
			received_events_url: 'https://api.github.com/users/ubemacapuno/received_events',
			type: 'User',
			site_admin: false
		},
		html_url: 'https://github.com/ubemacapuno/capa-tracker-sveltekit',
		description: 'Full-stack TypeScript + SvelteKit app for documenting CAPA reports',
		fork: false,
		url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit',
		forks_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/forks',
		keys_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/keys{/key_id}',
		collaborators_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/collaborators{/collaborator}',
		teams_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/teams',
		hooks_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/hooks',
		issue_events_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/issues/events{/number}',
		events_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/events',
		assignees_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/assignees{/user}',
		branches_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/branches{/branch}',
		tags_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/tags',
		blobs_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/git/blobs{/sha}',
		git_tags_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/git/tags{/sha}',
		git_refs_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/git/refs{/sha}',
		trees_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/git/trees{/sha}',
		statuses_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/statuses/{sha}',
		languages_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/languages',
		stargazers_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/stargazers',
		contributors_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/contributors',
		subscribers_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/subscribers',
		subscription_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/subscription',
		commits_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/commits{/sha}',
		git_commits_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/git/commits{/sha}',
		comments_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/comments{/number}',
		issue_comment_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/issues/comments{/number}',
		contents_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/contents/{+path}',
		compare_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/compare/{base}...{head}',
		merges_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/merges',
		archive_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/{archive_format}{/ref}',
		downloads_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/downloads',
		issues_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/issues{/number}',
		pulls_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/pulls{/number}',
		milestones_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/milestones{/number}',
		notifications_url:
			'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/notifications{?since,all,participating}',
		labels_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/labels{/name}',
		releases_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/releases{/id}',
		deployments_url: 'https://api.github.com/repos/ubemacapuno/capa-tracker-sveltekit/deployments',
		created_at: '2022-11-29T19:18:20Z',
		updated_at: '2024-02-05T19:03:03Z',
		pushed_at: '2023-11-12T18:00:17Z',
		git_url: 'git://github.com/ubemacapuno/capa-tracker-sveltekit.git',
		ssh_url: 'git@github.com:ubemacapuno/capa-tracker-sveltekit.git',
		clone_url: 'https://github.com/ubemacapuno/capa-tracker-sveltekit.git',
		svn_url: 'https://github.com/ubemacapuno/capa-tracker-sveltekit',
		homepage: '',
		size: 935,
		stargazers_count: 0,
		watchers_count: 0,
		language: 'Svelte',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 8,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: ['mongodb', 'svelte', 'sveltekit', 'typescript'],
		visibility: 'public',
		forks: 0,
		open_issues: 8,
		watchers: 0,
		default_branch: 'main',
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true
		},
		temp_clone_token: '',
		network_count: 0,
		subscribers_count: 2
	},
	{
		id: 507762720,
		node_id: 'R_kgDOHkPYIA',
		name: 'tortoise-tea-house-site',
		full_name: 'ubemacapuno/tortoise-tea-house-site',
		private: false,
		owner: {
			login: 'ubemacapuno',
			id: 97559559,
			node_id: 'U_kgDOBdCkBw',
			avatar_url: 'https://avatars.githubusercontent.com/u/97559559?v=4',
			gravatar_id: '',
			url: 'https://api.github.com/users/ubemacapuno',
			html_url: 'https://github.com/ubemacapuno',
			followers_url: 'https://api.github.com/users/ubemacapuno/followers',
			following_url: 'https://api.github.com/users/ubemacapuno/following{/other_user}',
			gists_url: 'https://api.github.com/users/ubemacapuno/gists{/gist_id}',
			starred_url: 'https://api.github.com/users/ubemacapuno/starred{/owner}{/repo}',
			subscriptions_url: 'https://api.github.com/users/ubemacapuno/subscriptions',
			organizations_url: 'https://api.github.com/users/ubemacapuno/orgs',
			repos_url: 'https://api.github.com/users/ubemacapuno/repos',
			events_url: 'https://api.github.com/users/ubemacapuno/events{/privacy}',
			received_events_url: 'https://api.github.com/users/ubemacapuno/received_events',
			type: 'User',
			site_admin: false
		},
		html_url: 'https://github.com/ubemacapuno/tortoise-tea-house-site',
		description: 'SvelteKit Website for Tortoise Tea House in Phoenix, AZ',
		fork: false,
		url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site',
		forks_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/forks',
		keys_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/keys{/key_id}',
		collaborators_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/collaborators{/collaborator}',
		teams_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/teams',
		hooks_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/hooks',
		issue_events_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/issues/events{/number}',
		events_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/events',
		assignees_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/assignees{/user}',
		branches_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/branches{/branch}',
		tags_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/tags',
		blobs_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/git/blobs{/sha}',
		git_tags_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/git/tags{/sha}',
		git_refs_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/git/refs{/sha}',
		trees_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/git/trees{/sha}',
		statuses_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/statuses/{sha}',
		languages_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/languages',
		stargazers_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/stargazers',
		contributors_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/contributors',
		subscribers_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/subscribers',
		subscription_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/subscription',
		commits_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/commits{/sha}',
		git_commits_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/git/commits{/sha}',
		comments_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/comments{/number}',
		issue_comment_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/issues/comments{/number}',
		contents_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/contents/{+path}',
		compare_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/compare/{base}...{head}',
		merges_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/merges',
		archive_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/{archive_format}{/ref}',
		downloads_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/downloads',
		issues_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/issues{/number}',
		pulls_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/pulls{/number}',
		milestones_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/milestones{/number}',
		notifications_url:
			'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/notifications{?since,all,participating}',
		labels_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/labels{/name}',
		releases_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/releases{/id}',
		deployments_url: 'https://api.github.com/repos/ubemacapuno/tortoise-tea-house-site/deployments',
		created_at: '2022-06-27T04:32:38Z',
		updated_at: '2024-02-05T19:02:44Z',
		pushed_at: '2022-11-23T17:16:41Z',
		git_url: 'git://github.com/ubemacapuno/tortoise-tea-house-site.git',
		ssh_url: 'git@github.com:ubemacapuno/tortoise-tea-house-site.git',
		clone_url: 'https://github.com/ubemacapuno/tortoise-tea-house-site.git',
		svn_url: 'https://github.com/ubemacapuno/tortoise-tea-house-site',
		homepage: '',
		size: 19338,
		stargazers_count: 0,
		watchers_count: 0,
		language: 'Svelte',
		has_issues: true,
		has_projects: true,
		has_downloads: true,
		has_wiki: true,
		has_pages: false,
		has_discussions: false,
		forks_count: 0,
		mirror_url: null,
		archived: false,
		disabled: false,
		open_issues_count: 0,
		license: null,
		allow_forking: true,
		is_template: false,
		web_commit_signoff_required: false,
		topics: [],
		visibility: 'public',
		forks: 0,
		open_issues: 0,
		watchers: 0,
		default_branch: 'main',
		permissions: {
			admin: true,
			maintain: true,
			push: true,
			triage: true,
			pull: true
		},
		temp_clone_token: '',
		network_count: 0,
		subscribers_count: 2
	}
]
